# Configuration passwords for Serverpod

shared:
  mySharedPassword: 'my password'

development:
  database: 'Mr_U7k63ZbR32LUMq7BQ0woyI8Lt6jVX'
  redis: '0-27mEze6tiA6tWNpahV6V6nHN-_93s4'
  serviceSecret: 'bFeYGNJ0a8FmvOyoQpZ5ogvblaZIT6j_'
  emailSecretHashPepper: 'OACyrikbWrTVRPNQxq08oyprZ02f_UKP'
  jwtHmacSha512PrivateKey: 'OhEfU26zG0NPSPoBfqNqQQuO7-ViW-Q8'
  jwtRefreshTokenHashPepper: 'DcTEXDFQ84wy-_Iq9a_SLHEg59D1XnoO'

test:
  database: 'svunBlPAjJgFZIEr5BEZFXqwz9m17Uv5'
  redis: 'Vid0ocQ3cqZIN098somAujHnD8j5PlJd'
  emailSecretHashPepper: 'ce6HHtAQFEFknKZAvNyjLGoWXN3P1-X6'
  jwtHmacSha512PrivateKey: 'UdDZW7c8bekhtE8nh-rWe6vywJtvhybV'
  jwtRefreshTokenHashPepper: 'mfgzU73cmuPsJj113ykLXZNwMEcuxaK1'

staging:
  database: 'GIOwHtZINh3yoUtVZyJVJU-0ByxvGXim'
  serviceSecret: 'eI1KZBTHQvHjGQjb9LmsSlr6v2a-ZW-2'
  emailSecretHashPepper: 'Gme_Ti5qIm6Z2p-rZK7sk90R-UBieD7g'
  jwtHmacSha512PrivateKey: 'D2KYg9YTTT3NbUC3kCK4gti1tlNT8Hf9'
  jwtRefreshTokenHashPepper: 'm3cezc-iCyvwzLUlthC2IYjXdRJahhC_'

production:
  database: 'Mr_U7k63ZbR32LUMq7BQ0woyI8Lt6jVX'
  redis: '0-27mEze6tiA6tWNpahV6V6nHN-_93s4'
  serviceSecret: 'GL1Cy89AsWK-uQjJ_cIsoVOE1AF_v9a1'
  emailSecretHashPepper: 'lrQoWSgnF03j2yMnPDH1qv_69Oy4Glzn'
  jwtHmacSha512PrivateKey: 'ny1ah-Sdr2az1TGOO0wTgK01Q9rEJXTX'
  jwtRefreshTokenHashPepper: 'LxYmDHxyyTDy318UXQmHTBDhW-HUGnSS'
